#include "arm_math.h"

#include "IIR_lpf_coefficients.h"
#include "IIR_hpf_coefficients.h"
 

#define N 512 

 

float32_t x1[N], x2[N], x[N]; 

 

int n; 

 

float32_t y_low[N];
float32_t y_high[N];

float32_t iirDF2TF32_low[4*numStages_low];
float32_t iirDF2TF32_high[4*numStages_high];
 

arm_biquad_cascade_df2T_instance_f32 S;

 

int main(void)

{

   uint16_t n; 



    for(n=0;n<N;n++)   

    {   

         x1[n] = arm_sin_f32(2000*PI*n/(96000/2));

         x2[n] = arm_sin_f32(16000*PI*n/(96000/2)); 

         x[n] = x1[n]+x2[n];

    }

   arm_biquad_cascade_df2T_init_f32(&S, numStages_low, h_low, iirDF2TF32_low);
		 // arm_biquad_cascade_df2T_init_f32(&S, numStages_high, h_high, iirDF2TF32_high);

   arm_biquad_cascade_df2T_f32(&S, x, y_low, n);
		//arm_biquad_cascade_df2T_f32(&S, x, y_high, n);

   arm_scale_f32(y_low, gain_low, y_low, N);
		//arm_scale_f32(y_high, gain_high, y_high, N);
   return(0); 

}